### ISSUE TITLE
Neovim instead vim

### ISSUE THREAD

**Issue by monomarh** [ARtoriouSs/dotfiles#1]
> "Neovim is exactly what it claims to be. It fixes every issue I have with Vim." —Geoff Greer

Try to use [Neovim](https://neovim.io/):

* Asynchronous plugin features (Jobs, Timers, Channels, JSON support)
* Vimscript Lambdas* 
* Built-in package manager
* Built-in terminal
* Better defaults without a config file

**Comment by ARtoriouSs** [comment]
Migrated https://github.com/ARtoriouSs/dotfiles/commit/6184d6009cd0eefb5ca3cbf62c0160d46a07963d :)
